name: "verify: server"

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'server/**'
      - '.github/workflows/verify-server.yml'

defaults:
  run:
    working-directory: server

jobs:
  verify:
    name: Verify there are no lint or typescript errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # ratchet:actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache-dependency-path: server

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run Knip
        run: npm run knip

      - name: Run ESLint
        run: npm run lint

      - name: Check for typescript errors
        run: npm run lint:tsc
