name: "verify: server"

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'server/**'
      - '.github/workflows/verify-server.yml'

defaults:
  run:
    working-directory: server

jobs:
  verify:
    name: Verify there are no lint or typescript errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # ratchet:actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache-dependency-path: server

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run Knip
        run: npm run knip

      - name: Run ESLint
        run: npm run lint

      - name: Check for typescript errors
        run: npm run lint:tsc
